### ISSUE TITLE
Non-existent challenges hangs indefinitely

### ISSUE THREAD

**Issue by Eiim** [ctfguide-tech/ctfguide#6]
Attempting to access a url like [https://ctfguide.tech/challenges/a](https://ctfguide.tech/challenges/a) hangs indefinitely. Other non-existent urls, like https://ctfguide.tech/a, simply 404, but non-existent challenge urls fail to.

**Comment by Eiim** [comment]
This also applies to https://ctfguide.tech/api/checksolution for invalid challenge ids

**Comment by Laphatize** [comment]
Being addressed in next patch
